### ISSUE TITLE
Someone need to take pictures of the venue

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#5]
**_Please replace my description of this task**_

**Comment by briandfoy** [comment]
I'm in New York and can take pictures. Tell me what you want, where it is, why you need each photo (so I can capture the intent) and so on.

**Comment by rpcme** [comment]
The venue does not allow general photography, but we can record talks.

The venue is here:
http://hsc.universitysettlement.org/hsc

Training:  Classroom 1 and Seminar 1
Talks: Classroom 2 & 3 combined.
Hackathon: Classroom 1 & 4

Why the YMCA?  Because what we pay goes directly to helping low income families in the downtown / Houston st. area.

And actually it's a pretty nice facility.
